/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as MusicRouteImport } from './routes/music'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as StreamingRouteImport } from './routes/streaming'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)

const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)

const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

const StreamingRoute = StreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/memories': typeof MemoriesRoute
  '/timeline': typeof TimelineRoute
  '/letters': typeof LettersRoute
  '/music': typeof MusicRoute
  '/chat': typeof ChatRoute
  '/search': typeof SearchRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminRoute
  '/streaming': typeof StreamingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/memories': typeof MemoriesRoute
  '/timeline': typeof TimelineRoute
  '/letters': typeof LettersRoute
  '/music': typeof MusicRoute
  '/chat': typeof ChatRoute
  '/search': typeof SearchRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminRoute
  '/streaming': typeof StreamingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/memories': typeof MemoriesRoute
  '/timeline': typeof TimelineRoute
  '/letters': typeof LettersRoute
  '/music': typeof MusicRoute
  '/chat': typeof ChatRoute
  '/search': typeof SearchRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminRoute
  '/streaming': typeof StreamingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/memories' | '/timeline' | '/letters' | '/music' | '/chat' | '/search' | '/login' | '/signup' | '/admin' | '/streaming'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/memories' | '/timeline' | '/letters' | '/music' | '/chat' | '/search' | '/login' | '/signup' | '/admin' | '/streaming'
  id: '__root__' | '/' | '/memories' | '/timeline' | '/letters' | '/music' | '/chat' | '/search' | '/login' | '/signup' | '/admin' | '/streaming'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemoriesRoute: typeof MemoriesRoute
  TimelineRoute: typeof TimelineRoute
  LettersRoute: typeof LettersRoute
  MusicRoute: typeof MusicRoute
  ChatRoute: typeof ChatRoute
  SearchRoute: typeof SearchRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminRoute: typeof AdminRoute
  StreamingRoute: typeof StreamingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming': {
      id: '/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof StreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemoriesRoute: MemoriesRoute,
  TimelineRoute: TimelineRoute,
  LettersRoute: LettersRoute,
  MusicRoute: MusicRoute,
  ChatRoute: ChatRoute,
  SearchRoute: SearchRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminRoute: AdminRoute,
  StreamingRoute: StreamingRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
